import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// import { WagmiProvider } from "wagmi";
// import { Web3Modal } from "@web3modal/react";
// import { config } from "../config";
// import { chains, providers } from "@web3modal/ethereum";
// import { QueryClient } from "@tanstack/react-query";
import { WagmiContextProvider } from "../providers/wagmi";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Pullix: Licensed Forex and Crypto CFD Trading Broker",
  description: "Generated by create next app",
};

// const modalConfig = {
//   theme: "dark",
//   accentColor: "default",
//   ethereum: {
//     appName: "Pullix",
//     chains: [chains.goerli, chains.polygonMumbai],
//     providers: [],
//     autoConnect: true,
//   },
//   projectId: "",
// };

// const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <WagmiContextProvider>{children}</WagmiContextProvider>
      </body>
    </html>
  );
}
